# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=45)),
                ('end_date', models.CharField(max_length=45)),
                ('plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('pw_hash', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('b_day', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trips',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelbuddy.Users'),
        ),
        migrations.AddField(
            model_name='groups',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelbuddy.Users'),
        ),
        migrations.AddField(
            model_name='groups',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelbuddy.Trips'),
        ),
    ]
