# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0002_auto_20170329_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='username',
        ),
    ]
